CLD3rd-Team4/Infra

- terraform/main.tf
- terraform/modules/eks/alb_controller_policy.tf
- terraform/modules/eks/irsa.tf
- terraform/modules/eks/main.tf
- terraform/modules/eks/outputs.tf
- terraform/modules/eks/security_group.tf
- terraform/modules/eks/variables.tf
- terraform/providers.tf
- 커스텀 IAM 정책 정의 및 역할에 연결
- ACM 모듈에 provider override 적용
> feat: ALB controller IRSA role & custom IAM policy

- terraform/main.tf
- terraform/modules/aurora/main.tf
- terraform/modules/aurora/outputs.tf
- terraform/modules/aurora/variables.tf
- terraform/outputs.tf
로컬에서 테스트가 안돼서 PR 올려서 Plan 테스트하려고 올립니다.
> fix: rds 클러스트가 서비스 갯수에 따라 추가되고 서비스명 반영되도록 수정

- terraform/k8s_helm.tf
- terraform/main.tf
awslb controller 사용을 위한 서브넷 태그 추가 및 디버깅을 위한 주석처리
- 서브넷에 로드밸런서 관련 태그 추가
- isito 관련 기능 전부 주석처리(디버깅용)
> fix: 서브넷 태그 추가 및 디버깅을 위한 주석처리

- terraform/k8s_helm.tf
helm 설치 부분 istio 관련 주석을 모두 해제하고 테스트 진행
> fix:디버깅용 주석 해제

- terraform/k8s_helm.tf
- terraform/modules/eks/addons.tf
- terraform/modules/eks/irsa.tf
ebs,efs csi 애드온 추가, istio-ingress 네임스페이스 변경
- pvc를 자동 추가하기 위해 ebs,efs csi 애드온을 추가했습니다. (프로메테우스에서 필요로함)
- istio-ingress의 네임스페이스를 변경했습니다.
> fix: ebs,efs csi 애드온 추가, istio-ingress 네임스페이스 변경

- argocd/service-schedule/envoy-grfc-http.yaml
envoy filter에서 .pb파일이 현재 비어있어 네트워크 오류를 야기하는 것으로 추측되어 주석처리
> fix: envoy filter 주석처리

- argocd/platform/config.yaml
> ENCRYPT KEY 삭제

- argocd/service-schedule/schedule.yaml
- scripts/setup-k8s-mac.sh
- scripts/setup-k8s-windows.bat
- scripts/values/alb-ingress-to-istio-ingress.yaml
- scripts/values/fluentbit-output.conf
스케줄서버 istio-proxy를 주석처리하고 디플로이먼트의 레플리카수 삭제했습니다.
> fix:istio-proxy주석처리

- terraform/main.tf
- eks:DescribeCluster 및 eks:ListClusters 권한 추가
- GitHub Actions에서 kubeconfig 업데이트 및 서비스 재시작을 위해 필요
- CI/CD 워크플로우의 kubectl 접근 문제 해결
> feat: GitHubActionsOIDCRole에 EKS 권한 추가

- terraform/modules/cloudfront/main.tf
- terraform/modules/cloudfront/outputs.tf
- terraform/modules/ecr/main.tf
- terraform/modules/s3/main.tf
- terraform/modules/s3/variables.tf
웹사이트용 버킷정책을 추가했습니다.
cloudfront에서만 웹사이트용 버킷에 접근가능하도록 수정했습니다.
> fix: 웹사이트용 버킷정책 추가

- argocd/platform/auth.yaml
- Auth 서비스용 Kubernetes 리소스 설정 추가
- Service: ClusterIP 타입으로 내부 통신만 허용
- Deployment: ECR 이미지 사용, 헬스체크 설정
- HPA: CPU/메모리 기반 1-3개 Pod 자동 확장
- Prometheus 모니터링 설정 포함
- Config Server 연결 테스트를 위한 완전한 배포 환경 구성
> feat: Auth 서비스 ArgoCD 배포 설정 추가

- argocd/demo/demo.yaml
- scripts/setup-k8s-windows.bat
fix:envoy 볼륨마운트 어노테이션에 Volume이 빠져있어 추가했습니다.
볼륨이 정확히 마운트되는지 확인이 필요합니다.
> fix:envoy 볼륨마운트 어노테이션 수정

- argocd/demo/envoy-grfc-http.yaml
셀렉터가 demo로 되어있어 오류가 발생해 demo-pod로 정확히 맞추도록 수정했습니다.
> fix:envoyfilter 셀렉터 demo-pod로 수정

- argocd/service-recommend/envoy-grpc-http.yaml
- argocd/service-recommend/recommend.yaml
- argocd/service-review/envoy-grpc-http.yaml
- argocd/service-review/review.yaml
- argocd/service-schedule/envoy-grpc-http.yaml
- argocd/service-schedule/schedule.yaml
정상적인 envoy 작동을 위해 현재 서버가 정상적으로 올라오지 않아 envoy 관련 설정을 모두 주석처리했습니다.
이후 서버가 정상작동 할 시에 주석해제 하시면 됩니다.
> cd:envoyfilter관련 설정 msa서버에서 주석처리

- terraform/main.tf
- terraform/modules/aurora/outputs.tf
- terraform/modules/db_provisioner/main.tf
- terraform/modules/db_provisioner/variables.tf
- terraform/variables.tf
db_provisioner 모듈을 새롭게 만들어서
프로바이더와 db 역할 관리를 하도록 하는것으로 프로바이더 종속성 문제를 해결하였습니다.
- 변경된 주요 파일/폴더
- 추가된 기능/수정된 기능 요약
테스트가 필요한 부분이나, 다음 작업과 연관되는 부분 정리
내가 기억하고 싶은 내용, 후속 작업 아이디어 등
> feat: aurora db 프로바이더 독립

- terraform/modules/cloudfront/main.tf
- terraform/modules/dynamodb/main.tf
무슨 작업을 완료했는지 간단하게 적기  
- 변경된 주요 파일/폴더
- 추가된 기능/수정된 기능 요약
테스트가 필요한 부분이나, 다음 작업과 연관되는 부분 정리
내가 기억하고 싶은 내용, 후속 작업 아이디어 등
> fix : cloudfront 헤더교채

- terraform/modules/cloudfront/main.tf
> cloude front 원복

- scripts/generate-sealed-secrets.sh
- scripts/setup-k8s-mac.sh
- terraform/main.tf
- terraform/modules/cloudwatch/main.tf
- terraform/modules/cloudwatch/outputs.tf
- terraform/modules/cloudwatch/variables.tf
- terraform/modules/lambda/main.tf
- terraform/modules/lambda/outputs.tf
- terraform/modules/lambda/slack_notifier.py
- terraform/modules/lambda/variables.tf
- terraform/modules/sns/main.tf
- terraform/modules/sns/outputs.tf
- terraform/modules/sns/variables.tf
- terraform/variables.tf
- 서비스별 독립적인 SNS 토픽 생성
- oauth, recommend, schedule 서비스 지원
- CloudWatch 알람 → SNS → Lambda → Slack 웹훅
- 서비스별 전용 Slack 채널로 알림 전송
- 알람 상세 정보 포함한 메시지 포맷
- **CPU 사용률**: 80% 임계값
- **메모리 사용량**: 1GB 임계값  
- **Read Latency**: 100ms 임계값
- **Write Latency**: 100ms 임계값
| 서비스 | DB 클러스터 | Slack 채널 |
|--------|-------------|------------|
| oauth | mapzip-dev-oauth-db | #1-platform |
| recommend | mapzip-dev-recommend-db | #1-recommend |
| schedule | mapzip-dev-schedule-db | #1-schedule |
- K8s 설정 스크립트 개선
- Sealed Secrets 생성 스크립트 업데이트
- DB 성능 이슈 실시간 감지
- 서비스별 담당팀에 즉시 알림
- 장애 대응 시간 단축
- `oauth_webhook_url`: OAuth 팀 Slack 웹훅 URL
- `recommend_webhook_url`: Recommend 팀 Slack 웹훅 URL  
- `schedule_webhook_url`: Schedule 팀 Slack 웹훅 URL
1. **Terraform Plan**: 리소스 생성 계획 확인
2. **Terraform Apply**: 모니터링 시스템 배포
3. …
> feat: DB monitoring system with SNS, Lambda, CloudWatch alarms

- terraform/modules/elasticache/main.tf
valkey serverless를 버전 8.1로 업데이트합니다.
> fix: valkey serverless 버전 8.1로 업데이트

- terraform/modules/lambda/slack_notifier.py
Lambda 함수에 상세한 디버깅 로그를 추가하여 SNS 메시지 구조 분석 및 문제점 파악
- ✅ 전체 SNS 이벤트 구조 로깅
- ✅ 파싱된 SNS 메시지 상세 로깅  
- ✅ 메트릭 정보 추출 과정 로깅
- ✅ 시간 변환 과정 상세 로깅
- ✅ 에러 처리 및 구체적 에러 메시지
- ✅ Slack 응답 본문 로깅
현재 슬랙 메시지에서 발견된 문제들:
- ❌ **시간 변환 실패**: UTC 시간이 KST로 변환되지 않음
- ❌ **임계값 정보 누락**: 으로 표시됨
- ❌ **메트릭 정보 누락**: 으로 표시됨
이 PR은 문제 원인 파악을 위한 임시 디버깅 코드입니다:
1. SNS 메시지 구조 확인
2. 메트릭 정보 추출 실패 원인 파악
3. 시간 변환 실패 원인 분석
4. 향후 수정 방향 결정
디버깅 로그 분석 후 실제 문제 수정 및 로그 정리 예정
> debug: Lambda 함수 디버깅 로그 추가

- argocd/platform/auth.yaml
- argocd/platform/config.yaml
- argocd/platform/gateway.yaml
- argocd/service-recommend/recommend.yaml
- argocd/service-review/review.yaml
- argocd/service-schedule/schedule.yaml
전체 서버에 롤링업데이트 설정을 추가했습니다.
게이트웨이 서버에 150초 이후에도 배포가 되지 않으면 실패 처리 설정을 추가했습니다.
> cd: 롤링 업데이트 설정 추가

- argocd/service-schedule/schedule.yaml
1. containers
2. initContainers
3. volumes
로 순서 변경
- 변경된 주요 파일/폴더
- 추가된 기능/수정된 기능 요약
테스트가 필요한 부분이나, 다음 작업과 연관되는 부분 정리
내가 기억하고 싶은 내용, 후속 작업 아이디어 등
> fix: initContainers 순서 변경

- scripts/values/grafana.yaml
- terraform/modules/eks/irsa.tf
- terraform/modules/eks/irsa_policy.tf
그라파나에서 cloudwatch 지표를 대시보드로 확인할 수 있게 irsa를 추가했습니다.
> infra: 그라파나 irsa추가

- terraform/modules/eks/irsa_policy.tf
Cluster Autoscaler의 IRSA 권한에 필요한 권한을 추가해줬습니다.
> fix:CA IRSA권한 추가

- terraform/main.tf
- terraform/modules/cloudwatch/main.tf
- terraform/modules/cloudwatch/variables.tf
Schedule cache 모니터링 추가 및 알람 메트릭 최적화로 효율적인 모니터링 구현
✅ **Schedule Cache 모니터링 추가**
- **새로운 클러스터**: `mapzip-dev-schedule-cache-serverless`
- **타입**: Serverless ElastiCache (
📊 **모니터링 메트릭 최소화 (12개 → 8개)
- ✅ **CPU 사용률** (80%) - 핵심 성능 지표
- ✅ **메모리 사용률** (1GB 임계값) - 용량 관리
- ✅ **읽기 지연시간** (100ms) - 사용자 경험
- ✅ **쓰기 지연시간** (100ms) - 데이터 일관성
- ✅ **CPU 사용률** (80%) - 캐시 서버 성능
- ✅ **메모리 사용률** (80%) - 캐시 용량 관리
- ❌ **연결 수** - 제거 (일반적으로 문제되지 않음)
- ❌ **캐시 히트율** - 제거 (애플리케이션 레벨 관심사)
- ✅ **읽기 스로틀** (5회) - 용량 부족 핵심 지표
- ✅ **쓰기 스로틀** (5회) - 용량 부족 핵심 지표
- ❌ **시스템 에러** - 제거 (AWS 콘솔에서 확인 가능)
- ❌ **사용자 에러** - 제거 (애플리케이션 로그에서 관리)
- `mapzip-dev-auth-cache-001` (OAuth)
- `mapzip-dev-recommend-cache-001` (Recommend)
- `mapzip-dev-review-cache-001` (Review)
- `mapzip-dev-schedule-cache-serverless` (Schedule) ← **새로 추가** …
> Add Schedule Cache Monitoring & Optimize Alert Metrics

- argocd/service-schedule/schedule.yaml
10초 간격으로 최대 30번 (총 5분) 동안 앱이 시작될 때까지 기다려줍니다.
- 변경된 주요 파일/폴더
- 추가된 기능/수정된 기능 요약
테스트가 필요한 부분이나, 다음 작업과 연관되는 부분 정리
내가 기억하고 싶은 내용, 후속 작업 아이디어 등
> fix: Istio 사이드카 에러

- terraform/modules/dynamodb/main.tf
Review 서비스 DynamoDB GSI 불일치 문제 해결
누락된 GSI 추가: RatingIndex, RecommendationIndex, AddressIndex
> Fix Review service DynamoDB GSI mismatch

- argocd/service-review/review.yaml
- scripts/update-review-image-latest.sh
> fix:redis 활성화, 이미지태그최신화

- terraform/modules/eks/irsa.tf
"arn:aws:dynamodb:${var.aws_region}:*:table/${var.common_prefix}revie… 추가
> "arn:aws:dynamodb:${var.aws_region}:*:table/${var.common_prefix}revie… 추가
